Update ReadMe.md
ProjectPythiaTutorials/tutorial-template pull request #1
Opened 2021-11-17 17:22 UTC by jukent

2021-11-17 21:13 UTC, ktyle requested changes
@jukent looks great! Suggested edits and questions below:

First section:

Since this section has no title, perhaps name it "Overview"?

Paragraph 3: "lower barrier of entry" --> "lower the barrier of entry"
P 3: "These new repositories differs from pythia-foundations" --> "These new repositories differ from the pythia-foundations"
P 3: "excercises" --> "exercises"
P3 : "preferred style" --> "preferred styles"

P4: Regarding "binderhub" ... might "binder" or "mybinder"  be better?

Should the "pythia-foundations" and "BinderHub" be web links instead of code-formatted blocks?

Organization section:

P1: "take" --> "takes"

2nd-to-last bullet point: add "e.g.," before "preparation steps, past videos ..." unless your intent is to make these three items mandatory and exclusive

Make "ESDS blog posts" a web link.

Contribution section:

"If your dataset is too large ... " Quantify this. Looks like a 100 MB limit per file unless Large File support is enabled, and then the limit is 2 GB (half of which is a 1GB per month bandwidth limit).
"By reach out to us here on GitHub", can you be more specific? Should a contributor make a PR, add an Issue, or something else?

"Contributors Guide" --> "Contributor's Guide"

2021-11-17 22:36 UTC, jukent commented
Thanks for your comments @ktyle! I've addressed them in the most recent push.

2021-11-18 02:44 UTC, ktyle commented
Looking good @jukent ... can you make the reference to the ESDS Blog Post a link (https://ncar.github.io/esds/blog/) ?

2021-11-18 18:09 UTC, ktyle approved these changes

2021-11-18 19:11 UTC, kmpaul approved these changes
Looks good!  Thanks, @jukent!

2021-11-18 19:11 UTC, merged